export const _products = [
  {
    id: "1",
    name: "Muhteşem Tasarım Elbise - Kahve",
    color: "Kahve",
    slug: "muhtesem-tasarim-elbise-kahve",
    currency: "TRY",
    price: 300,
    flag: "Yeni✨",
    rating: 4,
    ratingCount: 1,
    description: "test description",
    imageUrls: [
      {
        id: "01",
        src: "https://www.eflatunmoda.com/i/l/000/0000464_muhtesem-tasarim-elbise-kahve.jpeg",
        alt: "muhtesem-tasarim-elbise",
      },
    ],
    bodies: ["36", "38", "40", "42", "44"],
    category: "Elbise",
    linkedProducts: ["2", "3", "4"],
  },
  {
    id: "2",
    name: "Muhteşem Tasarım Elbise - Kırmızı",
    color: "Kırmızı",
    slug: "muhtesem-tasarim-elbise-kirmizi",
    currency: "TRY",
    price: 300,
    flag: "Yeni✨",
    rating: 4,
    ratingCount: 1,
    description: "test description",
    imageUrls: [
      {
        id: "01",
        src: "https://www.eflatunmoda.com/i/l/000/0000469_muhtesem-tasarim-elbise-kirmizi.jpeg",
        alt: "muhtesem-tasarim-elbise-kirmizi",
      },
    ],
    bodies: ["36", "38", "40", "42", "44"],
    category: "Elbise",
    linkedProducts: ["1", "3", "4"],
  },
  {
    id: "3",
    name: "Muhteşem Tasarım Elbise - Siyah",
    color: "Siyah",
    slug: "muhtesem-tasarim-elbise-siyah",
    currency: "TRY",
    price: 300,
    flag: "Yeni✨",
    rating: 4,
    ratingCount: 1,
    description: "test description",
    imageUrls: [
      {
        id: "01",
        src: "https://www.eflatunmoda.com/i/l/000/0000466_muhtesem-tasarim-elbise-siyah.jpeg",
        alt: "muhtesem-tasarim-elbise-siyah",
      },
    ],
    bodies: ["36", "38", "40", "42", "44"],
    category: "Elbise",
    linkedProducts: ["1", "2", "4"],
  },
  {
    id: "4",
    name: "Muhteşem Tasarım Elbise - Zümrüt",
    color: "Zümrüt",
    slug: "muhtesem-tasarim-elbise-zumrut",
    currency: "TRY",
    price: 300,
    flag: "Yeni✨",
    rating: 4,
    ratingCount: 1,
    description: "test description",
    imageUrls: [
      {
        id: "01",
        src: "https://www.eflatunmoda.com/i/l/000/0000462_muhtesem-tasarim-elbise-zumrut.jpeg",
        alt: "muhtesem-tasarim-elbise-zumrut",
      },
    ],
    bodies: ["36", "38", "40", "42", "44"],
    category: "Elbise",
    linkedProducts: ["1", "2", "3"],
  },
];
